### PR TITLE
Enable blacklist support

### PR DESCRIPTION
**Pull request by erikjon**
In an attempt to address issue #28: LicensHeaderManager replaces 3rd party license headers, I've added support for this. I've tested many scenarios with success. Please review.
Thanks!

### CODE REVIEW

**Comment by FlorianDecker** [comment]
Hi erikjon,

Thanks for the Pull Request! I like you take on the Problem described in the Issue. 

As a minor nitpick: You seem to use different settings than used elsewhere in the project. As a result there are some lines committed which only differ in code style.  

About your implementation: It is slightly different than the Solution proposed in the Issue #28 . 
While a Blacklist in the Options would certainly help in many cases, a ignorelist in the .licenseheader file, as proposed by @MichaelKetting, would probably be more flexible and futureproof.
You could apply the ignored Keywords more fine grained (per Project/Folder/Extension) and would be able to share it with everyone else working on the Project.

But i think we could add your Pull Request in the next Version and replace it, whenever the ignorelist in the .licenseheader file is implemented. I can probably review and test it properly next Week.

Opinions @drauch , @MichaelKetting ?

**Comment by MichaelKetting** [comment]
Hmm... it looks like I should have elaborated a bit more. The ignore list in the .licenseheader file is meant to specify the files to ignore, not a blacklist. I'd like to keep the feature discussion to the main thread, otherwise there's two sources of truth.

**Comment by MichaelKetting** [comment]
Okay, I've updated the feature discussion (https://github.com/rubicon-oss/LicenseHeaderManager/issues/28#issuecomment-211241291)

**Comment by erikjon** [comment]
Thanks to both of your for the comments. Florian, I'll double check my PR
and make sure I exclude any files that are only formatting/style-related.

As for the functionality, I misunderstood Michael's proposed solution. In
reviewing it again, I agree that a blacklist per .licenseheader file would
be much more effective and granular. At the same time, blacklisting by
filename has the potential for missing some files, particularly within a
large set of files. Perhaps there's a good way to filter by license content
within the local .licenseheader file. Let me think on this and get back to
you; I will have some time later this week to dig into this further.

Thanks, guys!
-Erik

**Comment by FlorianDecker** [comment]
Yeah i too misunderstood Michaels solution. 
Thank you for working of this!

If you have any ideas, please continue discussion in the issue thread #28 :)

**Comment by erikjon** [comment]
I'll discuss via the issue thread. Thanks again for the feedback. We're
doing a bunch of copyright changes right now due to an acquisition, so your
plugin has been very helpful! I'll keep you posted with my ideas.

**Comment by FlorianDecker** [comment]
While debugging an other issue i, unintentionally, used your build of LicenseHeaderManager and found an issue. The LicenseHeader does not get added if there are some comments without keywords on top of the file. This is due to your changes in the Function "ReplaceHeaderIfNecessary". 

Your change is understandable, as the Name of the Function does not imply that it not only replaces the LicenseHeader, but in some cases also just adds it. If you use that Code base for further development, please change the beaviour to match the current Version of the function.

**Comment by FlorianDecker** [comment]
As we are doing some housekeeping after the 2.0.0 release, i am going to close this pull request due to low activity. We will of course reopen it, if there are any updates.

**Pull request closed without merging**
